In [16]:
import numpy as np
arr = np.array([1, 2, 3])

In [17]:
print(arr)

[1 2 3]


In [18]:
a = np.array(10)

b = np.array([1, 2, 3])

c = np.array([[1, 2, 3], [4, 5, 6]])

d = np.array([[[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]]])

In [19]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [20]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [21]:
print(c.dtype)
print(d.dtype)

int64
int64


In [22]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [23]:
print(len(b))

3


In [24]:
l1 = [10, 20, 30]
l2 = [40, 50, 60]

l3 = np.array(l1)
l4 = np.array(l2)

In [25]:
%timeit [l1[i] * l2[i] for i in range(len(l1))]

390 ns ± 69.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [26]:
%timeit l3 * l4

954 ns ± 567 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [27]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
arr = np.arange(1, 11, 2)
print(arr)

[1 3 5 7 9]


In [29]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
x = np.arange(1, 17)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [31]:
x = x.reshape(2, 8)
print(x)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [32]:
x = np.arange(1, 17)

x = x.reshape(2, 4, 2)
print(x)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [33]:
x = np.arange(1, 17)

x = x.reshape(4, -1)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [34]:
x = np.arange(1, 17)

y = x.reshape(2, 4, -1)

print(y)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [35]:
y_flat = y.flatten()

print(y_flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [36]:
a = np.arange(2, 18, 2)

print(a)

[ 2  4  6  8 10 12 14 16]


In [37]:
print(a[2])

6


In [38]:
print(a[2])
print(a[4])
print(a[6])

6
10
14


In [39]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [40]:
print(a[2, 2])

9


In [41]:
b = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

In [42]:
print(b[0, 1, 2])

6


In [43]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
print(arr[1:5])

[2 3 4 5]


In [45]:
print(arr[5:])

[6 7 8 9]


In [46]:
print(arr[:5])

[1 2 3 4 5]


In [47]:
print(arr[1:7:2])

[2 4 6]


In [48]:
print(arr[::2])

[1 3 5 7 9]


In [49]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [50]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
print(a[2, 1:3])

[8 9]


In [52]:
print(a[:, 2])

[3 6 9]


In [53]:
print(a[:, 1:])

[[2 3]
 [5 6]
 [8 9]]


In [54]:
x1 = np.array([1, 2, 3, 4, 5])

In [55]:
x2 = x1

In [56]:
print(x1)
print(x2)

[1 2 3 4 5]
[1 2 3 4 5]


In [57]:
x2[0] = 10

In [58]:
print(x1)
print(x2)

[10  2  3  4  5]
[10  2  3  4  5]


In [59]:
x3 = x1.view()

In [60]:
print(x1.base)
print(x3.base)

None
[10  2  3  4  5]


In [61]:
print(np.shares_memory(x1, x3))

True


In [62]:
x3[0] = 100

In [63]:
print(x1)
print(x3)

[100   2   3   4   5]
[100   2   3   4   5]


In [64]:
x4 = x1.copy()

In [65]:
x4[-1] = 900

In [66]:
print(x1)
print(x4)

[100   2   3   4   5]
[100   2   3   4 900]


In [67]:
print(np.shares_memory(x1, x4))

False


In [68]:
print(np.hstack((x1, x4)))

[100   2   3   4   5 100   2   3   4 900]


In [69]:
print(np.vstack((x1, x4)))

[[100   2   3   4   5]
 [100   2   3   4 900]]


In [70]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [71]:
print(np.concatenate((arr1, arr2), axis=0))

[1 2 3 4 5 6]


In [72]:
print(np.concatenate((arr1.reshape(-1, 1),
                      arr2.reshape(-1, 1)), axis=1))

[[1 4]
 [2 5]
 [3 6]]


In [73]:
print(np.append(arr1, arr2))

[1 2 3 4 5 6]


In [74]:
print(np.insert(x1, 4, x4))

[100   2   3   4 100   2   3   4 900   5]


In [75]:
x2 = np.delete(x2, 1)

print(x2)

[100   3   4   5]
